CREATE TABLE `BALANCE` (
	`ID`			INT(11)			    NOT NULL AUTO_INCREMENT,
  	`BALANCE` 		INT(11) UNSIGNED    NOT NULL,
  	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

INSERT INTO BALANCE (BALANCE) VALUES (10000);

CREATE TABLE `INCOME` (
	`ID`			INT(11)			NOT NULL AUTO_INCREMENT,
  	`INCOME` 		INT(11) UNSIGNED 	NOT NULL,
  	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;